base_model_path: "stable-diffusion-v1-5/stable-diffusion-v1-5" #"/mnt/data4/siyoon/stable-diffusion-v1-5" #"/home/cvlab15/project/siyoon/i2i_control/checkpoints/sd-image-variations-diffusers" #"runwayml/stable-diffusion-v1-5" #'./pretrained_weights/sd-image-variations-diffusers'
vae_model_path: "stable-diffusion-v1-5/stable-diffusion-v1-5" #"/mnt/data4/siyoon/stable-diffusion-v1-5/vae"  #"runwayml/stable-diffusion-v1-5" #'./pretrained_weights/sd-vae-ft-mse'
# vae_model_path: "stabilityai/sd-vae-ft-mse"
pretrained_unet_path : "/mnt/data4/siyoon/reversed_checkpoits/model_1.safetensors" #"/mnt/data4/siyoon/controlnext_checkpoints/checkpoint-34400+17600+2400/model_1.safetensors" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-21000/unet_weight_increasements.bin" # "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/unet_weight_increasements.bin" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07/checkpoint-4200/model_1.safetensors" #model_1.safetensors"

net:
  reference_unet_path : "/mnt/data4/siyoon/reversed_checkpoits/model_1.safetensors" # "/mnt/data4/siyoon/controlnext_checkpoints/checkpoint-34400+17600+2400/model_1.safetensors" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-21000/unet_weight_increasements.bin" # "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/unet_weight_increasements.bin" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07/checkpoint-4200/model_1.safetensors" #model_1.safetensors"
  denoising_unet_path : "/mnt/data4/siyoon/reversed_checkpoits/model_1.safetensors" #"/mnt/data4/siyoon/controlnext_checkpoints/checkpoint-34400+17600+2400/model_1.safetensors" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-21000/unet_weight_increasements.bin" # "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/unet_weight_increasements.bin" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07/checkpoint-4200/model_1.safetensors" #model_1.safetensors"
  controlnext_path: "/mnt/data4/siyoon/reversed_checkpoits/model.safetensors" # "/mnt/data4/siyoon/controlnext_checkpoints/checkpoint-34400+17600+2400/model.safetensors" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-21000/controlnext.bin" #model.safetensors" #'./pretrained_weights/control_v11p_sd15_openpose/diffusion_pytorch_model.bin'
# pretrained_unet_path : "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/model_1.safetensors" # "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/unet_weight_increasements.bin" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07/checkpoint-4200/model_1.safetensors" #model_1.safetensors"
  load_lora : False
  # reference_unet_lora_path : "/mnt/data4/siyoon/i2i_control/bdd_1101/controlnext_final_checkpoint52400/train_semantic_lora_whole_frozen_dataaug_consistenttimesteps/no_norm_matching_module_include64_lr1.0e-5_res512_bs1x1/stage1/reference_unet-22000.pth"
  
  load_trained_reference : False 
  # reference_unet_full_path : "/mnt/data4/siyoon/i2i_control/bdd_1105/controlnext_final_checkpoint52400/train_ref_mat/_dataaug_consistenttimesteps/lr1.0e-5_res512_bs1x1/multi_head/stage1/reference_unet-38000.pth"
  trained_den : False
  # denoising_unet_full_path : "/mnt/data4/siyoon/i2i_control/bdd_1108/controlnext_final_checkpoint52400/train_densa_mat_deepmatch/dataaug_consistenttimesteps/lr1.0e-5_res512_bs1x1/multi_head_timestep-aware/stage1/denoising_unet-4000.pth"
  # matcher_path: "/mnt/data4/siyoon/i2i_control/bdd_1105/controlnext_final_checkpoint52400/whole_frozen_dataaug_consistenttimesteps/lr5.0e-6_res512_bs1x1/multi_head/stage1/matcher-5000.pth" #"/mnt/data4/siyoon/i2i_control/bdd_1103/controlnext_final_checkpoint52400/whole_frozen_dataaug_consistenttimesteps/no_norm_matching_module_include64_lr1.0e-5_res512_bs1x1/stage1/matcher-20000.pth" 
  matcher_path : "/mnt/data4/siyoon/i2i_control/bdd_1108/controlnext_reversed/train_densa_mat_deepmatch/dataaug_consistenttimesteps/lr1.0e-5_res512_bs1x1/multi_head_split_adapter_after_down0_cost_plusminus/stage1/matcher-25000.pth"
  #  "/mnt/data4/siyoon/i2i_control/bdd_1108/controlnext_final_checkpoint52400/train_densa_mat_deepmatch/dataaug_consistenttimesteps/lr1.0e-5_res512_bs1x1/multi_head_split_adapter/stage1/matcher-28000.pth"
  #"/mnt/data4/siyoon/i2i_control/bdd_1105/controlnext_final_checkpoint52400/whole_frozen_dataaug_consistenttimesteps/lr1.0e-5_res512_bs1x1/multi_head_timestep-aware/checkpoints/matcher-22000.pth" #"/mnt/data4/siyoon/i2i_control/bdd_1105/controlnext_final_checkpoint52400/train_ref_mat/_dataaug_consistenttimesteps/lr1.0e-5_res512_bs1x1/multi_head/stage1/matcher-38000.pth"
# net:
#   reference_unet_path : "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/model_1.safetensors" # "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/unet_weight_increasements.bin" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07/checkpoint-4200/model_1.safetensors" #model_1.safetensors"
#   denoising_unet_path : "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/model_1.safetensors" # "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/unet_weight_increasements.bin" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07/checkpoint-4200/model_1.safetensors" #model_1.safetensors"
#   controlnext_path: "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/model.safetensors" #model.safetensors" #'./pretrained_weights/control_v11p_sd15_openpose/diffusion_pytorch_model.bin'

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

data:
  val_width: 512 #512 
  val_height: 512 #512

validation:
  real_paths:
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a70faa46-6630da64.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/9a9da7d3-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/80985724-bc3fece0.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/9eb69cb0-42faf92d.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/8a66084a-5158b84e.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/91faccca-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/8ab12dec-59848511.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a9ad892b-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/971cbf48-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/8f737bfa-756ddb33.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/808ff399-79b2c310.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a02501c6-e1ed5f44.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/7d209219-ccdc1a09.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/7dc08598-f42e2015.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/7f3656b9-ef39e56d.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/9c94f476-8107ee6b.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/7e5ef657-a9ad0001.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/8dd5f9b7-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/9a60b3e7-789f9b00.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/ff55861e-a06b953c.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a8923b1f-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000835.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000830.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000835.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000845.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000850.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000865.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000870.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000875.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000530.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000535.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000540.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000545.jpg

    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7d22891c-224788c0.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7de0a101-68335d0a.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7df23ae0-00000000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7e1a88c5-66aa091b.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7e23ea75-d0830001.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7ea0c1bd-fe29369b.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7efc3f4d-00000000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8ac605d8-98fb991c.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8bffba2a-8fbc586f.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8c20378f-62c1b32e.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8c51607c-e71801fd.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8d72cada-899afec9.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8dd5f9b7-00000000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8df744f5-00000000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8df81748-4fe371e7.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8e718a5e-c5a827bf.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8f71e64e-6c9b9af0.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8fd046f2-93dc0000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8fd046f2-bb680001.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8fd046f2-e41d0001.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9b5a525e-36d1387e.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9b35ae98-6c105604.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9b338ed3-95770001.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9bb14814-4ddebd7a.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9bcccfec-e004fb23.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9d41951a-9782ea10.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9e5dafa1-0309776e.jpg
    
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9e555c8b-a7ee8541.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9ed56142-b87fa698.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/80b25f81-00000000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/83adc77e-c640d4cf.jpg

    # -  /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/96aed891-9c6b2ca9.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/96d80b29-a10fa25c.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/99bf045b-52568680.jpg
    
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/808ff399-79b2c310.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/808ff399-ad8116e6.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/808ff399-d8e0068e.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/821e597a-b29f6f56.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/841bab45-291a0b71.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/879b4c0b-95afdfcf.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/972dccc9-00000000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/8558d9b4-00000000.jpg
    
    - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/9d02c9cf-a022fe44.jpg
    - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/a06a4b0e-c5241837.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/93505616-aeb546f8.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/a0c88715-00000000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/a4afc890-ddb598fb.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/a5fa7888-00000000.jpg
    # - /mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/a34fa9b9-f978bc01.jpg
    
    
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a91b7555-00000605.jpg

    # - "/mnt/data1/CityScapes/leftImg8bit/val/frankfurt/frankfurt_000001_080830_leftImg8bit.png"
  seg_paths:
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7dc08598-f42e2015.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7d209219-ccdc1a09.png

    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7f3656b9-ef39e56d.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/9c94f476-8107ee6b.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7e5ef657-a9ad0001.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/8dd5f9b7-00000000.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a760566c-e45f7339.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/8a286021-385f1357.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/8c976e04-a838f2a6.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00001230.png
    - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/92411c47-8653c844.png
    - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/95b4f545-e2637c77.png
    
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/7dc08598-f42e2015/7dc08598-f42e2015.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/7dc08598-f42e2015/7dc08598-f42e2015_1.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/7dc08598-f42e2015/7dc08598-f42e2015_2.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/7dc08598-f42e2015/7dc08598-f42e2015_3.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/9c94f476-8107ee6b/9c94f476-8107ee6b_1.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/9c94f476-8107ee6b/9c94f476-8107ee6b_2.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/9c94f476-8107ee6b/9c94f476-8107ee6b_3.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/9c94f476-8107ee6b/9c94f476-8107ee6b.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/frankfurt_000001_080830_gtFine_color/frankfurt_000001_080830_gtFine_color.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/frankfurt_000001_080830_gtFine_color/frankfurt_000001_080830_gtFine_color_1.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/frankfurt_000001_080830_gtFine_color/frankfurt_000001_080830_gtFine_color_2.png"
    # - "/home/cvlab15/project/siyoon/seg2real24/seg_edit/frankfurt_000001_080830_gtFine_color/frankfurt_000001_080830_gtFine_color_3.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000830.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000835.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000845.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000850.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000865.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000870.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000875.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000605.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000530.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000535.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000540.png"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a91b7555-00000545.png"

  val_json: "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/customized_sem_seg_val.json"


# output_dir: "1108/multi-head_split_matcher_deepmatch_midup/ctrlx_like_step20_7.5_checkpoint8000/midup"
# output_dir : "tmp"
output_dir : "1121_appl/"