data:
  train_bs: 1
  train_width: 512
  train_height: 512
  train_seg_width: 512
  train_seg_height: 512
  real_images_path: "/mnt/data4/siyoon/bdd100k/bdd100k/images/100k/train/"
  seg_images_path: "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/train/" #"/media/dataset1/init_cond/sunny"
  mode: "default" #"retrieve_dino"
  cond_mode : "single"
  # Margin of frame indexes between ref and tgt images
  # sample_margin: 30
train_mode:
  train_matching_module: True
  train_semantic : False 
  train_denoising : False
  aug_mode : True
  consistent_timesteps: True 
  recon_reference : True

  train_semantic_lora : False
  train_semantic_sa : False
  train_denoising_lora : False

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: False #False
  max_train_steps: 500000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: False
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 1000


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  # clip_sample:         false

base_model_path: "stable-diffusion-v1-5/stable-diffusion-v1-5" #"/home/cvlab15/project/siyoon/i2i_control/checkpoints/sd-image-variations-diffusers" #"runwayml/stable-diffusion-v1-5" #'./pretrained_weights/sd-image-variations-diffusers'
vae_model_path: "stable-diffusion-v1-5/stable-diffusion-v1-5" #"stabilityai/sd-vae-ft-mse" #"runwayml/stable-diffusion-v1-5" #'./pretrained_weights/sd-vae-ft-mse'
controlnext_path: "/mnt/data4/siyoon/controlnext_checkpoints/checkpoint-34400+17600+2400/model.safetensors" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-21000/controlnext.bin" #model.safetensors" #'./pretrained_weights/control_v11p_sd15_openpose/diffusion_pytorch_model.bin'
pretrained_unet_path : "/mnt/data4/siyoon/controlnext_checkpoints/checkpoint-34400+17600+2400/model_1.safetensors" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-21000/unet_weight_increasements.bin" # "/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07_02/best/checkpoint-8400/unet_weight_increasements.bin" #"/mnt/data4/jeeyoung/checkpoints/controlnext_SD1.5_batch_size_16_10_07/checkpoint-4200/model_1.safetensors" #model_1.safetensors"
controlnext_scale : 1.0
pretrained_matching_module_path: None 

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True #False
pose_guider_pretrain: True

seed: 42
resume_from_checkpoint: "" #'/home/cvlab01/project/siyoon/Moore-AnimateAnyone/real_ref_seg_exp_output_lr5.0e-6/stage1/'
checkpointing_steps: 1000
save_model_epoch_interval: 1 
exp_name: 'stage1'
output_dir: '/mnt/data4/siyoon/i2i_control/bdd_1105/controlnext_final_checkpoint52400/whole_frozen_dataaug_consistenttimesteps/lr1.0e-5_res512_bs1x1/multi_head_timestep-aware'

validation:
  real_paths:
    - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a70faa46-6630da64.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/9a9da7d3-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/80985724-bc3fece0.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/9eb69cb0-42faf92d.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/8a66084a-5158b84e.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/91faccca-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/8ab12dec-59848511.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a9ad892b-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/971cbf48-00000000.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/8f737bfa-756ddb33.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/808ff399-79b2c310.jpg
    # # # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/99ebed9d-b6dd1203.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/a02501c6-e1ed5f44.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/9a60b3e7-789f9b00.jpg
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/images/10k/val/ff55861e-a06b953c.jpg


    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7d97d173-09388af3.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7daa6479-67988f3f.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7df23ae0-00000000.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7ef50949-51640000.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/val/7f0b6105-00000000.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/test/ac6e638d-7c84846d.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/test/ac9be3fe-790d1f8e.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/test/ac56c836-bdabca21.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/test/afdc295b-5efbee33.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/test/b4d9d4e7-00000000.jpg"
    # - "/mnt/data4/siyoon/bdd100k/bdd100k/images/10k/test/b666b95d-ec6681ac.jpg"
  seg_paths:
    - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7d209219-ccdc1a09.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7dc08598-f42e2015.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7f3656b9-ef39e56d.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/9c94f476-8107ee6b.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7e5ef657-a9ad0001.png
    # - /mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/8dd5f9b7-00000000.png
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/a02501c6-e1ed5f44.png
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/9a60b3e7-789f9b00.png
    # - /mnt/data4/jeeyoung/bdd100k/bdd100k/labels/10k/sem_seg/colormaps//val/ff55861e-a06b953c.png
  
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7d97d173-09388af3.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7daa6479-67988f3f.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7df23ae0-00000000.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7ef50949-51640000.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7f0b6105-00000000.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7d2f7975-e0c1c5a7.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7d209219-ccdc1a09.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7dc08598-f42e2015.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7e5ef657-a9ad0001.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7e788ad5-00000000.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7ee5d536-808b2dd5.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/7f3656b9-ef39e56d.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/8a66084a-5158b84e.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/8dd5f9b7-00000000.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/8fd046f2-bb680001.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/9c2b6b1e-917011ce.png"
  #   - "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/colormaps/val/9c94f476-8107ee6b.png"
  val_json: "/mnt/data4/siyoon/bdd100k/bdd100k/labels/10k/sem_seg/customized_sem_seg_val.json"