data:
  train_bs: 8
  train_width: 512
  train_height: 512
  train_seg_width: 512
  train_seg_height: 512
  real_images_path: "/mnt/data4/siyoon/bdd100k/bdd100k/images/100k/train/"
  seg_images_path: "/mnt/data4/siyoon/bdd100k/bdd100k/labels/sem_seg/colormaps/train/" #"/media/dataset1/init_cond/sunny"
  mode: "default" #"retrieve_dino"
  cond_mode : "single"
  # Margin of frame indexes between ref and tgt images
  # sample_margin: 30

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: False #False
  max_train_steps: 500000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: False
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 200


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

base_model_path: "/home/cvlab15/project/siyoon/i2i_control/checkpoints/sd-image-variations-diffusers" #"runwayml/stable-diffusion-v1-5" #'./pretrained_weights/sd-image-variations-diffusers'
vae_model_path: "stabilityai/sd-vae-ft-mse" #"runwayml/stable-diffusion-v1-5" #'./pretrained_weights/sd-vae-ft-mse'
image_encoder_path: "/home/cvlab15/project/siyoon/i2i_control/checkpoints/image_encoder" #"laion/CLIP-ViT-bigG-14-laion2B-39B-b160k" #'./pretrained_weights/sd-image-variations-diffusers/image_encoder'
controlnet_path: "/home/cvlab15/project/siyoon/controlnet/checkpoint-5200/controlnet" #'./pretrained_weights/control_v11p_sd15_openpose/diffusion_pytorch_model.bin'

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True
pose_guider_pretrain: True

seed: 42
resume_from_checkpoint: "" #'/home/cvlab01/project/siyoon/Moore-AnimateAnyone/real_ref_seg_exp_output_lr5.0e-6/stage1/'
checkpointing_steps: 200
save_model_epoch_interval: 1 
exp_name: 'stage1'
output_dir: '/mnt/data4/siyoon/i2i_control/bdd_0916/controlnet_checkpoint5200/only_controlnet_transform_revised_cfg/all_w_both_textprompt_lr1.0e-5_res512_bs8x1'